[package]
name = "eval_ast"
version = "0.1.0"
edition = "2021"

[dependencies]
risc0-zkvm = { version = "3.0.5", default-features = false, features = ["std"] }
dnf_core = { path = "../../crates/dnf_core", default-features = false }
rsa = {version = "=0.9.6", default-features = false, features = ["sha2", "pem"]}

sha2 = { version = "=0.10.8", default-features = false , features = ["oid"]}
serde = { version = "1.0", default-features = false, features = ["derive", "alloc"] }