
WHITESPACE  = _{ " " | "\t" | "\r" | "\n" }
Number      = @{ "-"? ~ ASCII_DIGIT+ }
Bool        = { "true" | "false" }
Str         = @{ "\"" ~ ( "\\\"" | "\\\\" | !("\"") ~ ANY )* ~ "\"" }


Ident = @{ (ASCII_ALPHANUMERIC | "_") ~ (ASCII_ALPHANUMERIC | "_") * ~ ("." ~ (ASCII_ALPHANUMERIC | "_") ~ (ASCII_ALPHANUMERIC | "_")*)* }

Keyword     = { "AND" | "OR" | "true" | "false" | "var" | "string" | "u64" | "i64" | "bool" | "schema" | "create" }
Type = {"bool" | "float" | "int" | "string"}