// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.

// Local Module imports
mod parser;
mod predata_processor;

// Workspace, project imports
use benchmarks::performance_benchmarks::{write_results_csv, Row};
use dnf_core::epl::ProgramAst;
use methods::{EVAL_AST_ELF, EVAL_AST_ID};
use predata_processor::create_events_indexes;
use rand::rngs::OsRng;
use risc0_zkvm::Receipt;
use risc0_zkvm::{default_prover, ExecutorEnv};
use rsa::signature::{RandomizedSigner, SignatureEncoding};
use rsa::{pkcs1::EncodeRsaPublicKey, pkcs1v15::SigningKey, RsaPrivateKey, RsaPublicKey};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

// Standard library imports
use std::env;
use std::fs::{self, File};
use std::path::Path;
use std::time::Instant;

fn main() {
    // Start total benchmark timer.
    let execution_timer = Instant::now();

    //Read CLI arguments
    // 1. input JSON relative to benchmarks/test_data
    // 2. DSL query string
    // 3. output CSV relative to  benchmarks/benchmark_results
    let file_name_arg = env::args()
        .nth(1)
        .expect("specify the file name --file_name.json");
    let base = "benchmarks/test_data";
    let base_path = Path::new(base).join(file_name_arg);
    let path = base_path.to_str().unwrap();

    let query_arg = env::args()
        .nth(2)
        .expect("Expected: query with in DSL syntax.");
    let out_file_arg = env::args().nth(3).expect("Specify the out put file here.");

    // Initilize the benchmark result entry row.
    let mut bench: Row = Row::new();

    // Read input file and collect meta data.
    let file_str = fs::read_to_string(path).unwrap();
    let file = File::open(path).unwrap();
    let file_size_bytes = file.metadata().unwrap().len();
    let file_bytes = file_str.as_bytes(); //host\src\example_vw_event_data_window_test.json
    let file_len: u32 = file_bytes.len().try_into().unwrap();

    // Generate RSA key pair to sign the telemetry data bytes.
    let mut rng = OsRng;
    let private_key = RsaPrivateKey::new(&mut rng, 2048).unwrap();
    let signing_key = SigningKey::<Sha256>::new(private_key.clone());

    let public_key = RsaPublicKey::from(&private_key);
    let public_key_der = public_key.to_pkcs1_der().unwrap().as_bytes().to_vec();

    let signature = signing_key.sign_with_rng(&mut rng, file_bytes).to_vec();
    let sig_length: u32 = signature.len().try_into().unwrap();

    // Pre-compute the event index list based on input file.
    let index_list = create_events_indexes(file_str.as_str());

    // Parse the DSL query into the AST used as guest input.
    let program_ast_result = parser::parse_source(&query_arg);
    let ast: ProgramAst = match program_ast_result {
        Err(e) => {
            print!("Error {}", e);
            return;
        }
        Ok(tree) => tree,
    };

    // Build zkVM executor environment.
    // Order of writing inputs, matches the order of the guest-side input reading.
    let env_timer = Instant::now();

    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    let env = ExecutorEnv::builder()
        .write(&ast)
        .unwrap()
        .write(&file_len)
        .unwrap()
        .write_slice(file_bytes)
        .write(&index_list)
        .unwrap()
        .write(&(public_key_der.len() as u32))
        .unwrap()
        .write_slice(&public_key_der)
        .write(&(sig_length as usize))
        .unwrap()
        .write_slice(&signature)
        .build()
        .unwrap();

    let env_time = env_timer.elapsed().as_secs();

    // Generate the proof and measure the proving time.
    let prover = default_prover();

    let t = Instant::now();
    let prove_info = prover.prove(env, EVAL_AST_ELF).unwrap();
    let proving_time = t.elapsed().as_secs();

    eprint!("Proving time is: {:?}", &proving_time);
    println!("\n");

    let receipt = prove_info.receipt;

    // Recompute the predicate hash on host-side.
    let recomputed_predicate_hash = recalculate_predicate_hash(&query_arg);

    // Verify the receipt and decode the guest journal.
    // Measure the verification time in ms.
    let verifier_timer = Instant::now();
    let (_result, attestation_commitment, attestation_sig, number_of_events) =
        verify_attestation(&receipt, EVAL_AST_ID);

    // Check Guest contains expected data signature and commitment.
    assert!(
        check_signature_alignment(signature, attestation_sig,),
        "The signatures should match!"
    );
    assert!(
        check_commitment(recomputed_predicate_hash, attestation_commitment),
        "Commitments should match."
    );
    let verify_time = verifier_timer.elapsed().as_millis();
    let execution_time = execution_timer.elapsed().as_secs();

    // Collect benchmark results in row.
    bench.set_number_events(number_of_events);
    bench.set_dsl_query(&query_arg);
    bench.set_env_time(env_time as u32);
    bench.set_exec_time(execution_time as u32);
    bench.set_input_bytes(file_size_bytes);
    bench.set_prove_time(proving_time as u32);
    bench.set_total_cycles(prove_info.stats.total_cycles as u32);
    bench.set_user_cycles(prove_info.stats.user_cycles as u32);
    bench.set_veri_time(verify_time as u64);
    bench.set_segments(prove_info.stats.segments as u32);

    // Write bechmark results to file.
    write_results_csv(vec![bench], &out_file_arg).unwrap();
}

// Data structures
#[derive(Serialize, Deserialize)]
pub struct Journal {
    pub evaluation_result: bool,
    pub logic_commitment: [u8; 32],
    pub signature: Vec<u8>,
    pub number_of_events: u32,
}

// Helper functions
pub fn verify_attestation(receipt: &Receipt, image_id: [u32; 8]) -> (bool, [u8; 32], Vec<u8>, u32) {
    receipt
        .verify(image_id)
        .expect("Data batch evaluated correct. ");

    let journal: Journal = receipt.journal.decode().expect("failed to decode journal");

    return (
        journal.evaluation_result,
        journal.logic_commitment,
        journal.signature,
        journal.number_of_events,
    );
}
pub fn recalculate_predicate_hash(query_string: &str) -> [u8; 32] {
    let dnf = parser::parse_source(&query_string);

    let ast: ProgramAst = match dnf {
        Err(e) => {
            print!("Error {}", e);
            return [
                23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
                23, 23, 23, 23, 23, 23, 23, 23, 23, 23, 23,
            ];
        }
        Ok(tree) => tree,
    };

    let digest = Sha256::digest(ast.to_bytes());
    let mut output = [0u8; 32];

    output.copy_from_slice(&digest);

    return output;
}

pub fn check_commitment(expected: [u8; 32], obtained: [u8; 32]) -> bool {
    expected == obtained
}

pub fn check_signature_alignment(issued: Vec<u8>, committed: Vec<u8>) -> bool {
    issued == committed
}
