// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.

use dnf_core::epl::ProgramAst;
use methods::{EVAL_AST_ELF, EVAL_AST_ID};
mod parser;
mod predata_processor;

use predata_processor::create_events_indexes;
use rand::rngs::OsRng;

use risc0_zkvm::{default_prover, ExecutorEnv};
use std::fs;

use std::time::Instant;

use rsa::signature::{RandomizedSigner, SignatureEncoding};
use rsa::{
    pkcs1::{EncodeRsaPrivateKey, EncodeRsaPublicKey, LineEnding},
    pkcs1v15::SigningKey,
    RsaPrivateKey, RsaPublicKey,
};
use sha2::Sha256;

fn main() {
    // Prepare AST based on source and pest parsing => Input for evaluation
    let mut rng = OsRng;
    let file_str = fs::read_to_string(r"host/src/example_vw_event_data_window_test.json").unwrap();
    let file_bytes = file_str.as_bytes(); //host\src\example_vw_event_data_window_test.json
    let file_len: u32 = file_bytes.len().try_into().unwrap();

    let private_key = RsaPrivateKey::new(&mut rng, 2048).unwrap();
    let public_key = RsaPublicKey::from(&private_key);

    let priv_pem = public_key.to_pkcs1_pem(LineEnding::LF).unwrap().to_string();
    let pub_pem = private_key
        .to_pkcs1_pem(LineEnding::LF)
        .unwrap()
        .to_string();

    fs::write("host/src/private_key.pem", &priv_pem).unwrap();
    fs::write("host/src/public_key.pem", &pub_pem).unwrap();

    let singing_key = SigningKey::<Sha256>::new(private_key.clone());

    let mut rng = OsRng;

    let public_key = RsaPublicKey::from(&private_key);
    let public_key_pem = public_key.to_pkcs1_der().unwrap().as_bytes().to_vec();

    let index_list = create_events_indexes(file_str.as_str());

    let signature = singing_key.sign_with_rng(&mut rng, file_bytes).to_vec();
    let sig_length: u32 = signature.len().try_into().unwrap();

    // Example user defined query string, first defining the data extraction than ASSERT a rule.
    // Note: the IDENTIFIER (e.g. dataFieldName) must exactly match the identifier used in the original JSON
    let source = r#"CREATE SCHEMA VehicleData (dataFieldName string, value int);
                          assert ALL VehicleData (dataFieldName == "profiles.targetSOCPercentage" AND value < 50); 
                          assert SESSION(VehicleData:start(value == 10) ->  VehicleData(value == 30) ->  VehicleData:end(value == 3) ); "#;
    // Make also sure the value comparing against has same data type as defined in the SCHEMA.

    let dnf = parser::parse_source(&source);

    let ast: ProgramAst = match dnf {
        Err(e) => {
            print!("Error {}", e);
            return;
        }
        Ok(tree) => tree,
    };

    println!("{:?}", &ast);

    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    let env = ExecutorEnv::builder()
        .write(&ast)
        .unwrap()
        .write(&file_len)
        .unwrap()
        .write_slice(file_bytes)
        .write(&index_list)
        .unwrap()
        .write(&(public_key_pem.len() as u32))
        .unwrap()
        .write_slice(&public_key_pem)
        .write(&(sig_length as usize))
        .unwrap()
        .write_slice(&signature)
        .build()
        .unwrap();
    let prover = default_prover();
    // measure proving time
    let t = Instant::now();
    let prove_info = prover.prove(env, EVAL_AST_ELF).unwrap();
    eprint!("Proving time is: {:?}", t.elapsed());
    println!("\n");
    let receipt = prove_info.receipt;

    // Receive the boolean result and print it.
    let _output: bool = receipt.journal.decode().unwrap();
    println!("The query result is: {}", _output);

    // verify the result, returned from the guest-side evaluation
    receipt.verify(EVAL_AST_ID).unwrap();
}
