//! Benchmark CLI: signs a test-data batch, parses the query given as an
//! argument, extracts+indexes its events, runs the real zkVM proof, and
//! records timing/size results via `benchmarks::performance_benchmarks`.
//! Args: `<file_name.json> <query_string> <out_file.csv>`.

// These constants represent the RISC-V ELF and the image ID generated by risc0-build.
// The ELF is used for proving and the ID is used for verification.

use dnf_core::epl::ProgramAst;
use dnf_core::input_extractor::{efficient_event_extraction, grap_event_string};
use dnf_core::interpreter::Event;
use methods::{EVAL_AST_ELF, EVAL_AST_ID};
mod parser;
mod predata_processor;
use predata_processor::create_events_indexes;
use rand::rngs::OsRng;
use risc0_zkvm::{default_prover, ExecutorEnv};
use std::env;
use std::fs::{self, File};
use std::io::Read;
use colored::Colorize;
use std::path::Path;
use std::time::Instant;
use benchmarks::performance_benchmarks::{write_results_csv, Row};
use rsa::signature::{RandomizedSigner, SignatureEncoding};
use rsa::{
    pkcs1::{EncodeRsaPrivateKey, EncodeRsaPublicKey, LineEnding},
    pkcs1v15::SigningKey,
    RsaPrivateKey, RsaPublicKey,
};
use sha2::Sha256;

fn main() {
    let execution_timer = Instant::now();

    //Read environment CLI args.
    let file_name_arg = env::args()
        .nth(1)
        .expect("specify the file name --file_name.json");
    let base = "benchmarks/test_data";
    let base_path = Path::new(base).join(file_name_arg);
    let path = base_path.to_str().unwrap();

    let query_arg = env::args().nth(2).expect("Expected: entered query string!");

    let out_file_arg = env::args().nth(3).expect("Specify the out put file here.");

    // Set-up new performance measurement.
    let mut bench: Row = Row::new();

    // Prepare AST based on source and pest parsing => Input for evaluation
    let mut rng = OsRng;
    let file_name = path; // r"host/src/example_vw_event_data_window_test.json";
    let file_str = fs::read_to_string(file_name).unwrap();
    let file = File::open(file_name).unwrap();
    let file_size_bytes = file.metadata().unwrap().len();
    let file_bytes = file_str.as_bytes(); //host\src\example_vw_event_data_window_test.json
    let file_len: u32 = file_bytes.len().try_into().unwrap();

    let private_key = RsaPrivateKey::new(&mut rng, 2048).unwrap();
    let public_key = RsaPublicKey::from(&private_key);

    let priv_pem = public_key.to_pkcs1_pem(LineEnding::LF).unwrap().to_string();
    let pub_pem = private_key
        .to_pkcs1_pem(LineEnding::LF)
        .unwrap()
        .to_string();

    fs::write("host/src/private_key.pem", &priv_pem).unwrap();
    fs::write("host/src/public_key.pem", &pub_pem).unwrap();

    let singing_key = SigningKey::<Sha256>::new(private_key.clone());

    let mut rng = OsRng;

    let public_key = RsaPublicKey::from(&private_key);
    let public_key_pem = public_key.to_pkcs1_der().unwrap().as_bytes().to_vec();

    let index_list = create_events_indexes(file_str.as_str());

    let len = &index_list.len().to_string().purple();

    println!(
        "{} {}",
        "Expected total number of events in the file:".magenta(),
        len
    );

    let signature = singing_key.sign_with_rng(&mut rng, file_bytes).to_vec();
    let sig_length: u32 = signature.len().try_into().unwrap();



    let dnf = parser::parse_source(&query_arg);

    let ast: ProgramAst = match dnf {
        Err(e) => {
            print!("Error {}", e);
            return;
        }
        Ok(tree) => tree,
    };

    println!("{:?}", &ast);

    let mut host_events = Vec::new();
    let copied_ast = ast.schemas[0].clone();

    for i in &index_list {
        let grabed_events = grap_event_string(*i, file_bytes);
        host_events.push(grabed_events);
    }

    let mut extracted_events = Vec::new();
    for e in host_events {
        let event = efficient_event_extraction(copied_ast.clone(), e.as_bytes());
        extracted_events.push(event.clone());
    }
    println!("");
    println!(
        "{} {:?} ",
        "Expected events are :".green(),
        extracted_events
    );

    let env_timer = Instant::now();
    tracing_subscriber::fmt()
        .with_env_filter(tracing_subscriber::filter::EnvFilter::from_default_env())
        .init();

    let env = ExecutorEnv::builder()
        .write(&ast)
        .unwrap()
        .write(&file_len)
        .unwrap()
        .write_slice(file_bytes)
        .write(&index_list)
        .unwrap()
        .write(&(public_key_pem.len() as u32))
        .unwrap()
        .write_slice(&public_key_pem)
        .write(&(sig_length as usize))
        .unwrap()
        .write_slice(&signature)
        .build()
        .unwrap();
    let env_time = env_timer.elapsed().as_secs();

    let prover = default_prover();
    // measure proving time
    let t = Instant::now();
    let prove_info = prover.prove(env, EVAL_AST_ELF).unwrap();
    let proving_time = t.elapsed().as_secs();
    eprint!("Proving time is: {:?}", &proving_time);
    println!("\n");
    let receipt = prove_info.receipt;

    // Receive the boolean result and print it.
    let _output: bool = false; // receipt.journal.decode().unwrap();
    println!("The query result is: {}", _output);

    // Debug Output
    let _debug_output: u32 = receipt.journal.decode().unwrap();
    println!(
        "{}{}",
        "Number of events processed in the GUEST:".green(),
        _debug_output
    );

    let verifier_timer = Instant::now();
    // verify the result, returned from the guest-side evaluation
    receipt.verify(EVAL_AST_ID).unwrap();
    let verifiy_time = verifier_timer.elapsed().as_millis();

    let execution_time = execution_timer.elapsed().as_secs();

    // Collect the benchmark results:
    bench.set_number_events(_debug_output);
    bench.set_dsl_query(&query_arg);
    bench.set_env_time(env_time as u32);
    bench.set_exec_time(execution_time as u32);
    bench.set_input_bytes(file_size_bytes);
    bench.set_prove_time(proving_time as u32);
    bench.set_total_cycles(prove_info.stats.total_cycles as u32);
    bench.set_user_cycles(prove_info.stats.user_cycles as u32);
    bench.set_veri_time(verifiy_time as u64);
    bench.set_segments(prove_info.stats.segments as u32);

    write_results_csv(vec![bench], &out_file_arg).unwrap();
}
