//! Parses EPL DSL source text into a [`ProgramAst`].
//!
//! `DnfParser` is generated by `pest_derive` from the grammar files below;
//! `parse_source` drives that PEG parser and then walks the resulting parse
//! tree (`build_*` functions) into the typed AST used by the interpreter.

#![allow(clippy::upper_case_acronyms, clippy::result_large_error)]

//use std::sync::mpsc::RecvTimeoutError;

use std::collections::linked_list;

use dnf_core::ast::{Conjunction, Disjunction, Operator, Pred, Term};
use dnf_core::epl::{
    AggOperation, Aggregate, AssertRule, Attribute, AttributeList, CountWindow, Itype, PatternRule,
    ProgramAst, Quantifier, Schema, Session, TimeUnit, TimeWindow, Window,
};
use pest::Parser;
use pest_derive::Parser;

//use risc0_zkvm_platform::syscall::bigint::WIDTH_WORDS;

/// PEG parser for the EPL DSL, combining the schema/rule syntax
/// (`epl-dsl.pest`), shared terminals (`common.pest`) and the DNF
/// predicate grammar (`dnf.pest`) into a single rule set.
#[derive(Parser)]
//#[grammar = "grammar.pest"]
#[grammar = "epl-dsl.pest"]
#[grammar = "common.pest"]
#[grammar = "dnf.pest"]

pub struct DnfParser;

/// Parses a full EPL source string into a [`ProgramAst`].
///
/// The `program` rule matches the whole input, so it always yields exactly
/// one top-level pair; `build_program` then walks its children into the AST.
pub fn parse_source(source: &str) -> Result<ProgramAst, pest::error::Error<Rule>> {
    let mut pairs = DnfParser::parse(Rule::program, source)?;
    //let ast = build_dnf(pairs);
    // Ok(ast)

    let program_pair = pairs.next().unwrap();
    Ok(build_program(program_pair))
}

fn build_program(program: pest::iterators::Pair<Rule>) -> ProgramAst {
    let mut schemas = Vec::new();
    let mut assert_rules = Vec::new();
    let mut aggregates = Vec::new(); //TODO can be changed into a simple Predicate (lower effort in evaluation).
    let mut window_rule = None;
    let mut pattern_rule: Option<PatternRule> = None;
    let mut session: Option<Session> = None;

    for p in program.into_inner() {
        match p.as_rule() {
            Rule::schema => schemas.push(create_schema(p)),
            Rule::assert_rule => assert_rules.push(create_assert_rule(p)),
            Rule::aggregate_rule => aggregates.push(create_aggregate_assert_rule(p)),
            Rule::pattern_rule => pattern_rule = create_pattern_rule(p),
            Rule::window_rule => {
                window_rule = Some(create_window(p));
            }
            Rule::session => session = Some(create_session(p)),
            Rule::EOI => {}
            _ => {}
        }
    }

    return ProgramAst {
        schemas,
        assert_rules,
        aggregates,
        window_rule,
        pattern_rule,
        session,
    };
}

fn create_session(pair: pest::iterators::Pair<Rule>) -> Session {
    let mut sequence: Vec<Disjunction> = Vec::new();

    let mut it = pair.into_inner();
    let start_end_rule = it.next().unwrap();
    let mut inner = start_end_rule.into_inner();

    let start_ident = inner.next().unwrap();
    let mut ident = start_ident.as_str();
    let start_dnf = inner.next().unwrap();
    let start_dis = start_dnf.into_inner().next().unwrap();
    let dis_s = build_disjunction(start_dis);
    sequence.push(dis_s);

    let end_dnf = inner.next_back().unwrap();
    let end_ident = inner.next_back().unwrap();
    let end_dis = end_dnf.into_inner().next().unwrap();
    let dis_e = build_disjunction(end_dis);

    for ident_atom in inner {
        let mut atom_inner = ident_atom.into_inner();
        ident = atom_inner.next().unwrap().as_str();

        let dnf = atom_inner.next().unwrap();
        let dis = dnf.into_inner().next().unwrap();

        sequence.push(build_disjunction(dis));
    }

    sequence.push(dis_e);
    return Session {
        identifier: String::from(ident),
        session_sequence: sequence,
    };
}

fn create_window(pair: pest::iterators::Pair<Rule>) -> Window {
    let mut it = pair.into_inner();
    let ident_rule = it.next().unwrap();
    let window_pair = it.next().unwrap(); // TimeWindow or CountWindow

    match window_pair.as_rule() {
        Rule::TimeWindow => {
            let mut inner = window_pair.into_inner();
            let width_pair = inner.next().unwrap();
            let unit_pair = inner.next().unwrap();

            Window::TimeWindow(TimeWindow {
                w_width: build_term(width_pair),
                time_unit: build_time_unit(unit_pair),
            })
        }
        Rule::CountWindow => {
            let mut inner = window_pair.into_inner();
            let width_pair = inner.next().unwrap();

            Window::CountWindow(CountWindow {
                w_width: width_pair
                    .as_str()
                    .parse()
                    .expect("Parsed as u64 expected!"),
            })
        }
        _ => unreachable!("Not supported type of Window. Allowed are: TimeWindow or CountWindow."),
    }
}

fn build_time_unit(pair: pest::iterators::Pair<Rule>) -> TimeUnit {
    match pair.as_str() {
        "ms" => TimeUnit::MS,
        "s" => TimeUnit::S,
        "min" => TimeUnit::MIN,
        "h" => TimeUnit::H,
        "d" => TimeUnit::D,
        _ => unreachable!("Not a supported time unit. Only (ms, s, min, h, d)"),
    }
}

fn create_pattern_rule(pair: pest::iterators::Pair<Rule>) -> Option<PatternRule> {
    let mut links: Vec<Disjunction> = Vec::new();
    let mut ident: String = "".into();

    for ident_atom in pair.into_inner() {
        let mut atom_inner = ident_atom.into_inner();
        ident = String::from(atom_inner.next().unwrap().as_str());

        let dnf = atom_inner.next().unwrap();
        let dis = dnf.into_inner().next().unwrap();

        links.push(build_disjunction(dis));
    }

    return Some(PatternRule {
        identifier: ident,
        pattern_sequence: links,
    });
}
fn ident_to_string(ident: Term) -> String {
    match ident {
        Term::Ident(s) => s,
        _ => unimplemented!("Function implemented for Ident::Str(s) to String."),
    }
}

fn create_aggregate_assert_rule(pair: pest::iterators::Pair<Rule>) -> AssertRule {
    let mut dnf_pair = pair.into_inner().next().unwrap();
    let dnf: Vec<Disjunction> = match dnf_pair.as_rule() {
        Rule::Disjunction => vec![build_disjunction(dnf_pair)],
        Rule::dnf_statement => build_dnf(dnf_pair.into_inner()),
        other => unreachable!("Not expected other execution path!"),
    };

    return AssertRule {
        //TODO can be changed into simple predicate over the evaluated aggregat function like (SUM(value) < 56)
        ident: get_aggreage_assert_ident(dnf.clone()).unwrap(),
        rule: dnf,
        quantifier: Quantifier::ALL,
    };
}

fn get_aggreage_assert_ident(dnf: Vec<Disjunction>) -> Option<String> {
    let aggregate = &dnf.first()?.conj.first()?.preds.first()?.lhs;
    match aggregate {
        Term::Aggregate(a) => Some(a.ident.clone()),
        _ => None,
    }
}

fn get_aggreage_assert_op(dnf: Vec<Disjunction>) -> Option<AggOperation> {
    let aggregate = &dnf.first()?.conj.first()?.preds.first()?.lhs;
    match aggregate {
        Term::Aggregate(a) => Some(a.operation.clone()),
        _ => None,
    }
}

fn build_agg_operator(pair: pest::iterators::Pair<Rule>) -> AggOperation {
    match pair.as_str() {
        "MAX" => AggOperation::MAX,
        "COUNT" => AggOperation::COUNT,
        "MIN" => AggOperation::MIN,
        "AVG" => AggOperation::AVG,
        "MEDIAN" => AggOperation::MEDIAN,
        "STDDEV" => AggOperation::STDDEV,
        "MAXEVER" => AggOperation::MAXEVER,
        "MINEVER" => AggOperation::MINEVER,
        "SUM" => AggOperation::SUM,
        _ => unimplemented!("This aggregation operation is not supported!"),
    }
}

fn create_schema(pair: pest::iterators::Pair<Rule>) -> Schema {
    match pair.as_rule() {
        Rule::schema => {
            let mut it = pair.into_inner();
            let ident = build_ident(it.next().unwrap());
            let attr_list = build_attribute_list(it.next().unwrap());

            return Schema {
                ident,
                attribute_list: attr_list,
            };
        }
        _ => unreachable!("Only the Schema Rule is expected here"),
    }
}

fn create_assert_rule(pair: pest::iterators::Pair<Rule>) -> AssertRule {
    match pair.as_rule() {
        Rule::assert_rule => {
            let mut it = pair.into_inner();

            let quant = build_quantifer(it.next().unwrap());
            let ident = build_ident(it.next().unwrap());
            let dnf_pair = it.next().unwrap();

            let dnf: Vec<Disjunction> = match dnf_pair.as_rule() {
                Rule::Disjunction => vec![build_disjunction(dnf_pair)],
                Rule::dnf_statement => build_dnf(dnf_pair.into_inner()),
                other => unreachable!("Not expected other execution path!"),
            };

            return AssertRule {
                ident,
                rule: dnf,
                quantifier: quant,
            };
        }
        _ => unreachable!("Rule::assert_rule is expected here!"),
    }
}

fn build_quantifer(pair: pest::iterators::Pair<Rule>) -> Quantifier {
    match pair.as_rule() {
        Rule::quantifier => {
            let q_op = pair.as_str().to_string();

            if q_op == "ANY" {
                return Quantifier::ANY;
            } else if q_op == "ALL" {
                return Quantifier::ALL;
            } else {
                panic!("Unknown quantifier: {}", q_op);
            }
        }
        _ => unreachable!("Must be Identfier!"),
    }
}

fn build_attribute_list(pair: pest::iterators::Pair<Rule>) -> AttributeList {
    match pair.as_rule() {
        Rule::attribute_list => {
            //let mut it = pair.into_inner();

            let mut list: Vec<Attribute> = Vec::new();

            for inner in pair.into_inner() {
                list.push(build_attribute(inner));
            }
            return AttributeList { list };
        }
        _ => unreachable!("Should be an attribute list rule!"),
    }
}

fn build_attribute(pair: pest::iterators::Pair<Rule>) -> Attribute {
    match pair.as_rule() {
        Rule::attribute => {
            let mut it = pair.into_inner();
            let ident = build_ident(it.next().unwrap());
            let mut t: Itype = build_type(it.next().unwrap());
            return Attribute {
                i_type: t,
                ident: ident,
            };
        }
        _ => unreachable!("unexpected Term: {:?}", pair.as_rule()),
    }
}

fn build_ident(pair: pest::iterators::Pair<Rule>) -> String {
    match pair.as_rule() {
        Rule::Ident => pair.as_str().to_string(),
        _ => unreachable!("Must be Identfier!"),
    }
}

fn build_type(pair: pest::iterators::Pair<Rule>) -> Itype {
    match pair.as_str() {
        "string" => Itype::String,
        "int" => Itype::Int,
        "bool" => Itype::Bool,
        "float" => Itype::Float,
        _ => unreachable!(
            "Per Definition limited number of supported types (int, string, bool, float)"
        ),
    }
}

fn build_term(pair: pest::iterators::Pair<Rule>) -> Term {
    match pair.as_rule() {
        Rule::Int => Term::Int(pair.as_str().parse().unwrap()),
        Rule::Bool => Term::Bool(pair.as_str() == "true"),
        Rule::Float => Term::Float(pair.as_str().parse().unwrap()),
        Rule::aggregate => build_aggregate(pair),
        // Assuming your grammar returns quoted strings like "hi"
        Rule::Str => {
            let s = pair.as_str();
            // remove surrounding quotes
            let inner = &s[1..s.len().saturating_sub(1)];
            Term::Str(inner.to_string())
        }

        Rule::Ident => Term::Ident(pair.as_str().to_string()),

        _ => unreachable!("unexpected Term: {:?}", pair.as_rule()),
    }
}

fn build_aggregate(pair: pest::iterators::Pair<Rule>) -> Term {
    let mut it = pair.into_inner();

    let op = build_agg_operator(it.next().unwrap());
    let ident = build_ident(it.next().unwrap());

    return dnf_core::ast::Term::Aggregate(Aggregate {
        ident: ident,
        operation: op,
    });
}

fn build_operator(pair: pest::iterators::Pair<Rule>) -> Operator {
    match pair.as_str() {
        "==" => Operator::Eq,
        "!=" => Operator::NEq,
        ">" => Operator::Gr,
        "<" => Operator::Sm,
        "<=" => Operator::SmEq,
        ">=" => Operator::GrEq,
        _ => unreachable!("Unknown operator: {:?}", pair.as_str()),
    }
}

fn build_predicate(pair: pest::iterators::Pair<Rule>) -> Pred {
    let mut it = pair.into_inner();
    let lhs = build_term(it.next().unwrap());
    let op = build_operator(it.next().unwrap());
    let rhs = build_term(it.next().unwrap());

    Pred { lhs, op, rhs }
}

fn build_clause(pair: pest::iterators::Pair<Rule>) -> Conjunction {
    let preds = pair
        .into_inner()
        .filter(|p| p.as_rule() == Rule::Pred)
        .map(build_predicate)
        .collect();

    Conjunction { preds }
}

fn build_disjunction(pair: pest::iterators::Pair<Rule>) -> Disjunction {
    let clauses = pair
        .into_inner()
        .filter(|p| p.as_rule() == Rule::Conjunction)
        .map(build_clause)
        .collect();

    Disjunction { conj: clauses }
}

fn build_dnf(pairs: pest::iterators::Pairs<Rule>) -> Vec<Disjunction> {
    let mut ast: Vec<Disjunction> = Vec::new();

    for p in pairs {
        if let Rule::Disjunction = p.as_rule() {
            ast.push(build_disjunction(p));
        }
    }

    return ast;
}
